#!/bin/sh
printf '%s\n' "$*" >>"$SAYALL_TEST_SYSTEMCTL_LOG"
if [ "$*" = '--user is-active sayall.service' ]; then
  state=${SAYALL_TEST_LEGACY_STATE:-inactive}
  printf '%s\n' "$state"
  [ "$state" = active ] && exit 0
  exit 3
fi
